import { useState, useEffect } from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { expenseAPI } from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import toast from 'react-hot-toast';

const PERIODS = [
  { value: 'thisMonth', label: 'This Month' },
  { value: 'lastMonth', label: 'Last Month' },
  { value: 'thisYear', label: 'This Year' },
  { value: 'all', label: 'All Time' },
  { value: 'custom', label: 'Custom Range' },
];

const toISODate = (d) =>
  `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;

const getRange = (period, from, to) => {
  const now = new Date();
  const y = now.getFullYear();
  const m = now.getMonth();
  if (period === 'thisMonth') return { start: toISODate(new Date(y, m, 1)), end: toISODate(new Date(y, m + 1, 0)), label: 'This Month' };
  if (period === 'lastMonth') return { start: toISODate(new Date(y, m - 1, 1)), end: toISODate(new Date(y, m, 0)), label: 'Last Month' };
  if (period === 'thisYear') return { start: toISODate(new Date(y, 0, 1)), end: toISODate(new Date(y, 11, 31)), label: 'This Year' };
  if (period === 'all') return { start: null, end: null, label: 'All Time' };
  return { start: from || null, end: to || null, label: from && to ? `${from} to ${to}` : 'Custom Range' };
};

const formatAmount = (n) => `Rs. ${Math.round(n).toLocaleString('en-IN')}`;

const BRAND = [237, 101, 52];
const DARK = [38, 32, 29];
const MUTED = [122, 112, 100];
const MARGIN = 42;

function drawPageFooters(doc, user) {
  const width = doc.internal.pageSize.getWidth();
  const height = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= doc.getNumberOfPages(); i++) {
    doc.setPage(i);
    doc.setDrawColor(232, 226, 218);
    doc.setLineWidth(0.8);
    doc.line(MARGIN, height - 22, width - MARGIN, height - 22);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...MUTED);
    doc.text(`Generated by paisa. for ${user.name}`, MARGIN, height - 10);
    doc.text(`Page ${i} of ${doc.getNumberOfPages()}`, width - MARGIN, height - 10, { align: 'right' });
  }
}

function buildPdf({ user, expenses, total, count, avg, categoryTotals, monthlyTotals, rangeLabel }) {
  const doc = new jsPDF('p', 'pt', 'a4');
  const width = doc.internal.pageSize.getWidth();

  doc.setFillColor(...DARK);
  doc.rect(0, 0, width, 92, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(...BRAND);
  doc.text('paisa.', MARGIN, 48);
  doc.setFontSize(13);
  doc.setTextColor(255, 253, 248);
  doc.setFont('helvetica', 'normal');
  doc.text('Daily Expense Report', MARGIN, 68);

  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  doc.text(`Prepared for: ${user.name} (${user.email})`, width - MARGIN, 38, { align: 'right' });
  doc.text(`Period: ${rangeLabel}`, width - MARGIN, 54, { align: 'right' });
  doc.text(`Generated: ${new Date().toLocaleString('en-GB')}`, width - MARGIN, 70, { align: 'right' });

  let y = 116;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(...DARK);
  doc.text('Summary', MARGIN, y);
  y += 8;

  autoTable(doc, {
    startY: y,
    head: [['Total Spent', 'Transactions', 'Average / Transaction']],
    body: [[formatAmount(total), String(count), formatAmount(avg)]],
    theme: 'grid',
    headStyles: { fillColor: BRAND, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 10 },
    styles: { fontSize: 11, cellPadding: 9, textColor: DARK },
    margin: { left: MARGIN, right: MARGIN },
  });
  y = doc.lastAutoTable.finalY + 26;

  const categoryRows = Object.entries(categoryTotals)
    .sort((a, b) => b[1] - a[1])
    .map(([name, value]) => [name, formatAmount(value), `${total ? ((value / total) * 100).toFixed(1) : 0}%`]);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(...DARK);
  doc.text('Spending by Category', MARGIN, y);
  y += 8;

  autoTable(doc, {
    startY: y,
    head: [['Category', 'Amount', '% of Total']],
    body: categoryRows,
    theme: 'striped',
    headStyles: { fillColor: DARK, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 10 },
    styles: { fontSize: 10.5, cellPadding: 7, textColor: DARK },
    columnStyles: { 1: { halign: 'right' }, 2: { halign: 'right' } },
    margin: { left: MARGIN, right: MARGIN },
  });
  y = doc.lastAutoTable.finalY + 26;

  const monthRows = Object.entries(monthlyTotals).map(([name, value]) => [name, formatAmount(value)]);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(...DARK);
  doc.text('Monthly Breakdown', MARGIN, y);
  y += 8;

  autoTable(doc, {
    startY: y,
    head: [['Month', 'Amount']],
    body: monthRows,
    theme: 'striped',
    headStyles: { fillColor: DARK, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 10 },
    styles: { fontSize: 10.5, cellPadding: 7, textColor: DARK },
    columnStyles: { 1: { halign: 'right' } },
    margin: { left: MARGIN, right: MARGIN },
  });
  y = doc.lastAutoTable.finalY + 26;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(...DARK);
  doc.text('All Transactions', MARGIN, y);

  const expenseRows = expenses.map((e) => [
    new Date(e.date).toLocaleDateString('en-US', { day: '2-digit', month: 'short', year: 'numeric' }),
    e.title,
    e.category,
    e.paymentMethod,
    e.notes || '',
    formatAmount(e.amount),
  ]);

  autoTable(doc, {
    startY: y + 8,
    head: [['Date', 'Title', 'Category', 'Payment', 'Notes', 'Amount']],
    body: expenseRows,
    theme: 'striped',
    headStyles: { fillColor: BRAND, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9.5 },
    styles: { fontSize: 9.5, cellPadding: 6, textColor: DARK },
    columnStyles: { 5: { halign: 'right', fontStyle: 'bold' } },
    columnWidths: [72, 110, 78, 72, 155, 80],
    margin: { left: MARGIN, right: MARGIN },
  });

  drawPageFooters(doc, user);
  doc.save(`paisa-report-${rangeLabel.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.pdf`);
}

export default function ReportModal({ onClose }) {
  const { user } = useAuth();
  const [period, setPeriod] = useState('thisMonth');
  const [from, setFrom] = useState('');
  const [to, setTo] = useState('');
  const [rangeLabel, setRangeLabel] = useState('This Month');
  const [expenses, setExpenses] = useState([]);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);

  useEffect(() => {
    const range = getRange(period, from, to);
    setRangeLabel(range.label);
    setLoading(true);
    const params = {};
    if (range.start) params.startDate = range.start;
    if (range.end) params.endDate = range.end;
    expenseAPI.getAll(params)
      .then((res) => setExpenses(res.data))
      .catch(() => toast.error('Failed to load expenses'))
      .finally(() => setLoading(false));
  }, [period, from, to]);

  const total = expenses.reduce((sum, e) => sum + e.amount, 0);
  const count = expenses.length;
  const avg = count ? Math.round(total / count) : 0;
  const categoryTotals = expenses.reduce((acc, e) => {
    acc[e.category] = (acc[e.category] || 0) + e.amount;
    return acc;
  }, {});
  const monthlyTotals = expenses.reduce((acc, e) => {
    const key = new Date(e.date).toLocaleString('default', { month: 'short', year: 'numeric' });
    acc[key] = (acc[key] || 0) + e.amount;
    return acc;
  }, {});

  const handleDownload = () => {
    if (count === 0) return toast.error('No expenses in this period to report');
    setDownloading(true);
    try {
      buildPdf({ user, expenses, total, count, avg, categoryTotals, monthlyTotals, rangeLabel });
      toast.success('Report downloaded');
    } catch (err) {
      console.error(err);
      toast.error('Failed to generate PDF');
    } finally {
      setDownloading(false);
    }
  };

  const categoryList = Object.entries(categoryTotals).sort((a, b) => b[1] - a[1]);

  return (
    <div className="fixed inset-0 bg-black/75 backdrop-blur-sm flex items-center justify-center z-50 p-4" onClick={onClose}>
      <div className="bg-surface-900 border border-surface-700 rounded-3xl w-full max-w-lg max-h-[90vh] overflow-y-auto shadow-2xl" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between px-6 py-4 border-b border-surface-800">
          <div>
            <p className="text-brand-300 text-[11px] font-semibold uppercase tracking-[.16em] mb-1">Reports</p>
            <h2 className="page-title text-xl font-bold text-white">Generate a report</h2>
          </div>
          <button onClick={onClose} className="text-surface-400 hover:text-white transition-colors p-1 rounded-md hover:bg-surface-800">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <div className="p-6 space-y-5">
          <div>
            <label className="block text-xs font-medium text-surface-400 mb-1.5">Period</label>
            <select className="input-field" value={period} onChange={(e) => setPeriod(e.target.value)}>
              {PERIODS.map((p) => <option key={p.value} value={p.value}>{p.label}</option>)}
            </select>
          </div>

          {period === 'custom' && (
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-medium text-surface-400 mb-1.5">From</label>
                <input type="date" className="input-field" value={from} onChange={(e) => setFrom(e.target.value)} />
              </div>
              <div>
                <label className="block text-xs font-medium text-surface-400 mb-1.5">To</label>
                <input type="date" className="input-field" value={to} onChange={(e) => setTo(e.target.value)} />
              </div>
            </div>
          )}

          {loading ? (
            <div className="flex justify-center py-10">
              <div className="w-7 h-7 border-2 border-surface-700 border-t-brand-500 rounded-full animate-spin" />
            </div>
          ) : (
            <>
              <div className="grid grid-cols-3 gap-3">
                <div className="rounded-xl bg-surface-800/60 border border-surface-700 p-3">
                  <p className="text-[11px] font-medium text-surface-400 uppercase tracking-[.1em]">Total</p>
                  <p className="text-base font-bold text-white mt-1">Rs. {Math.round(total).toLocaleString('en-IN')}</p>
                </div>
                <div className="rounded-xl bg-surface-800/60 border border-surface-700 p-3">
                  <p className="text-[11px] font-medium text-surface-400 uppercase tracking-[.1em]">Entries</p>
                  <p className="text-base font-bold text-white mt-1">{count}</p>
                </div>
                <div className="rounded-xl bg-surface-800/60 border border-surface-700 p-3">
                  <p className="text-[11px] font-medium text-surface-400 uppercase tracking-[.1em]">Average</p>
                  <p className="text-base font-bold text-white mt-1">Rs. {Math.round(avg).toLocaleString('en-IN')}</p>
                </div>
              </div>

              <div>
                <p className="text-xs font-semibold text-surface-300 mb-2">Top categories</p>
                {categoryList.length === 0 ? (
                  <p className="text-sm text-surface-500 text-center py-4">No expenses in this period</p>
                ) : (
                  <div className="space-y-1.5">
                    {categoryList.slice(0, 5).map(([name, value], index) => (
                      <div key={name} className="flex items-center gap-2 text-sm">
                        <span className="w-2.5 h-2.5 rounded-full flex-shrink-0 bg-brand-500" style={{ opacity: 1 - index * 0.12 }} />
                        <span className="text-surface-300 flex-1 truncate">{name}</span>
                        <span className="text-surface-400 font-medium tabular-nums">{formatAmount(value)}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </>
          )}

          <div className="flex gap-3 pt-1">
            <button type="button" onClick={onClose} className="btn-secondary flex-1">Cancel</button>
            <button onClick={handleDownload} disabled={loading || downloading || count === 0} className="btn-primary flex-1 flex items-center justify-center gap-2">
              {downloading && <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />}
              {downloading ? 'Generating...' : 'Download PDF'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
